parameters:
    datatable.class: Ali\DatatableBundle\Util\Datatable

services:
    address_book_type:
        class: Xtreem\AddressBookBundle\Form\AddressBookType
        tags:
            - { name: form.type, alias: address_book_type }

    address_type:
        class: Xtreem\AddressBookBundle\Form\AddressType
        tags:
            - { name: form.type, alias: address_type }

    address_book_service:
        class: Xtreem\AddressBookBundle\Service\AddressBookService

    datatable:
        class: "%datatable.class%"
        arguments: [ "@service_container" ]
        scope: prototype

    datatable.twig.extension:
        class: Ali\DatatableBundle\Twig\Extension\AliDatatableExtension
        arguments: [ "@service_container" ]
        tags:
            -  { name: twig.extension }